repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'source .venv/bin/activate || source venv/bin/activate || source env/bin/activate && python -m pytest'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]