from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class OwInputAbstractLocatieRef(BaseModel):
    def get_code(self) -> Optional[str]:
        return None


class OwInputAmbtsgebiedLocatieRef(OwInputAbstractLocatieRef):
    pass


class OwInputGebiedLocatieRef(OwInputAbstractLocatieRef):
    code: str

    def get_code(self) -> Optional[str]:
        return self.code


class OwInputGebiedengroepLocatieRef(OwInputAbstractLocatieRef):
    code: str

    def get_code(self) -> Optional[str]:
        return self.code



class OwInputAmbtsgebied(BaseModel):
    source_uuid: str
    administrative_borders_id: str
    domain: str
    valid_on: str
    title: str


class OwInputRegelingsgebied(BaseModel):
    source_uuid: str


class OwInputLocatie(BaseModel):
    # These represent Locaties in the GIO which is an API.area
    source_code: str
    title: str
    geometry_id: str


class OwInputGeoGio(BaseModel):
    # This will make a Gebied for each locatie
    source_code: str
    title: str
    locaties: List[OwInputLocatie]


class OwInputGebiedengroep(BaseModel):
    # This is generated by API.Object_Type=gebiedengroep which has 1 or more gebied. And can be pointed towards API.Object_Type=maatregel etc
    # This will make a ow_gebiedengroep and allows the ow_tekstdeel to point to this
    source_code: str
    title: str
    geogio: OwInputGeoGio


class OwInputGebiedsaanwijzing(BaseModel):
    source_code: str
    title: str
    indication_type: str
    indication_group: str
    location_refs: List[OwInputAbstractLocatieRef]

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def get_unique_key(self) -> str:
        return f"{self.source_type}-{self.source_code}-{self.indication_type}-{self.indication_group}"

    def __hash__(self):
        return hash((self.source_type, self.source_code, self.indication_type, self.indication_group))

    def __eq__(self, other):
        if not isinstance(other, type(self)):
            return False
        return self.get_unique_key() == other.get_unique_key()


class OwInputPolicyObject(BaseModel):
    source_uuid: str
    source_code: str
    wid: str
    element: str
    location_refs: List[OwInputAbstractLocatieRef]

    model_config = ConfigDict(arbitrary_types_allowed=True)
